const reactProps = [
  'onClick',
  'onContextMenu',
  'onDoubleClick',
  'onDrag',
  'onDragEnd',
  'onDragEnter',
  'onDragExit',
  'onDragLeave',
  'onDragOver',
  'onDragStart',
  'onDrop',
  'onMouseDown',
  'onMouseEnter',
  'onMouseLeave',
  'onMouseMove',
  'onMouseOut',
  'onMouseOver',
  'onMouseUp',
  'className',
  'onMouseLeave',
  'onChange',
  'onFocus',
  'onBlur',
  'onMouseMove',
  'maxLength',
  'onSubmit',
  'htmlFor',
  'selected',
];

export default reactProps;
